# Generated by Django 3.1.2 on 2020-11-19 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgName', models.CharField(blank=True, default='', max_length=200)),
                ('Al1', models.CharField(blank=True, default=models.CharField(blank=True, default='', max_length=200), max_length=100)),
                ('Al2', models.CharField(blank=True, default='', max_length=100)),
                ('Al3', models.CharField(blank=True, default='', max_length=100)),
                ('district', models.CharField(blank=True, default='', max_length=40)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='India', max_length=100)),
                ('pinCode', models.IntegerField(default=0)),
                ('logo', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speakerName', models.CharField(max_length=100)),
                ('speakerPic', models.ImageField(blank=True, upload_to='')),
                ('speakerLinkedIn', models.URLField(blank=True)),
                ('speakerIG', models.URLField(blank=True)),
                ('speakerFB', models.URLField(blank=True)),
                ('speakerTwitter', models.URLField(blank=True)),
                ('speakerWebSite', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partName', models.CharField(max_length=100)),
                ('partCountry', models.CharField(max_length=100)),
                ('partContact', models.BigIntegerField(blank=True)),
                ('partMail', models.EmailField(blank=True, max_length=254)),
                ('partPic', models.ImageField(blank=True, upload_to='')),
                ('partOrg', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='events.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrganizerName', models.CharField(max_length=100)),
                ('OrganizerContactNumber', models.BigIntegerField(blank=True)),
                ('OrganizerMail', models.EmailField(blank=True, max_length=254)),
                ('OrganizerPic', models.ImageField(blank=True, upload_to='')),
                ('OrganizerOrganization', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='events.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(default='', max_length=100)),
                ('eventDescription', models.TextField(blank=True, default='', max_length=1000)),
                ('eventStartTime', models.DateTimeField(blank=True)),
                ('eventEndTime', models.DateTimeField(blank=True)),
                ('eventVenue', models.CharField(blank=True, max_length=200)),
                ('eventURL', models.URLField(blank=True)),
                ('eventSpeaker', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='events.speaker')),
            ],
        ),
    ]
