# Generated by Django 3.1.2 on 2020-11-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_participant_partevents'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventPoster',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
